# Generated by Django 4.0.5 on 2022-09-06 16:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunesBorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('shape_leng', models.FloatField()),
                ('dis_elec', models.IntegerField()),
                ('cir_sena', models.IntegerField()),
                ('cod_comuna', models.IntegerField()),
                ('codregion', models.IntegerField()),
                ('st_area_sh', models.FloatField()),
                ('st_length_field', models.FloatField()),
                ('region', models.CharField(max_length=60)),
                ('comuna', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
