# Generated by Django 4.0.5 on 2022-09-17 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_sales_date_joined'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='good',
        ),
        migrations.RemoveField(
            model_name='score',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='score',
            name='shop',
        ),
        migrations.AddField(
            model_name='score',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sales'),
        ),
    ]
