# Generated by Django 4.0.5 on 2022-08-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_good_image_good_price_unitmeasurement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
