# Generated by Django 4.0.5 on 2022-08-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
