# Generated by Django 4.0.5 on 2022-11-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_good_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='takeable',
            field=models.BooleanField(default=True),
        ),
    ]
