# Generated by Django 4.0.5 on 2022-08-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_usercustomer_shop_usercustomer_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
