# Generated by Django 4.0.5 on 2022-08-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_usercustomer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='personal_location_equal_trade_location',
            field=models.BooleanField(default=False),
        ),
    ]
