# Generated by Django 4.0.5 on 2022-08-23 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_usercustomer_personal_location_equal_trade_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 1, 18, 50, 156114)),
        ),
    ]
