# Generated by Django 4.0.5 on 2022-08-25 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0008_alter_usercustomer_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 18, 45, 35, 972632)),
        ),
    ]
