# Generated by Django 4.0.5 on 2022-09-09 23:29

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0002_alter_sales_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='provider',
        ),
        migrations.AddField(
            model_name='sales',
            name='delivery_point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(srid=4326, x=0, y=0), srid=4326),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 19, 29, 56, 381031)),
        ),
    ]
