# Generated by Django 4.0.5 on 2022-09-15 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_viewed_sales_client_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='client_viewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 13, 25, 31, 384071)),
        ),
    ]
