# Generated by Django 4.0.5 on 2022-09-21 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_sales_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 22, 2, 56, 216398)),
        ),
        migrations.AddField(
            model_name='sales',
            name='dispatch_help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.dispatchhelp'),
        ),
    ]
