# Generated by Django 4.0.5 on 2022-11-04 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_dispatchhelp_alter_sales_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 13, 20, 7, 615350)),
        ),
    ]
