# Generated by Django 4.0.5 on 2022-11-11 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_sales_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 22, 32, 14, 770868)),
        ),
    ]
